import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_performance/firebase_performance.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:workmanager/workmanager.dart';
import 'core/app.dart';
import 'core/di/injection.dart';
import 'core/services/background_service.dart';
import 'core/services/notification_service.dart';
import 'core/services/admob_service.dart';
import 'core/services/analytics_service.dart';
import 'core/utils/app_logger.dart';
import 'firebase_options.dart';

// Background task dispatcher
@pragma('vm:entry-point')
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    switch (task) {
      case BackgroundService.fetchJobsTask:
        await BackgroundService.fetchAndSyncJobs();
        break;
      case BackgroundService.cleanExpiredJobsTask:
        await BackgroundService.cleanExpiredJobs();
        break;
      case BackgroundService.sendDeadlineRemindersTask:
        await BackgroundService.sendDeadlineReminders();
        break;
    }
    return Future.value(true);
  });
}

Future<void> main() async {
  await runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();

      // System UI configuration
      SystemChrome.setSystemUIOverlayStyle(
        const SystemUiOverlayStyle(
          statusBarColor: Colors.transparent,
          statusBarIconBrightness: Brightness.light,
          navigationBarColor: Colors.transparent,
        ),
      );
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.portraitDown,
      ]);

      // Initialize Firebase
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      // Initialize Crashlytics
      FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

      // Initialize Hive local database
      await Hive.initFlutter();
      await _registerHiveAdapters();
      await _openHiveBoxes();

      // Initialize services
      await NotificationService.initialize();
      await AdMobService.initialize();
      await AnalyticsService.initialize();

      // Initialize background worker (auto job fetch every 3 hours)
      await Workmanager().initialize(callbackDispatcher, isInDebugMode: false);
      await _scheduleBackgroundTasks();

      // Setup dependency injection
      await setupDependencies();

      AppLogger.info('✅ RozgarX initialized successfully');

      runApp(
        const ProviderScope(
          child: RozgarXApp(),
        ),
      );
    },
    (error, stack) => FirebaseCrashlytics.instance.recordError(error, stack, fatal: true),
  );
}

Future<void> _registerHiveAdapters() async {
  // Hive adapters registered here (generated by hive_generator)
  // Hive.registerAdapter(JobModelAdapter());
  // Hive.registerAdapter(UserModelAdapter());
}

Future<void> _openHiveBoxes() async {
  await Hive.openBox('settings');
  await Hive.openBox('cached_jobs');
  await Hive.openBox('user_data');
  await Hive.openBox('offline_jobs');
  await Hive.openBox('exam_schedule');
  await Hive.openBox('syllabus_cache');
}

Future<void> _scheduleBackgroundTasks() async {
  // Auto fetch new jobs every 3 hours
  await Workmanager().registerPeriodicTask(
    'fetch_jobs_periodic',
    BackgroundService.fetchJobsTask,
    frequency: const Duration(hours: 3),
    constraints: Constraints(
      networkType: NetworkType.connected,
    ),
    backoffPolicy: BackoffPolicy.linear,
    backoffPolicyDelay: const Duration(minutes: 15),
  );

  // Clean expired jobs daily at midnight
  await Workmanager().registerPeriodicTask(
    'clean_expired_jobs',
    BackgroundService.cleanExpiredJobsTask,
    frequency: const Duration(hours: 24),
    initialDelay: const Duration(hours: 1),
  );

  // Send deadline reminders daily at 8am
  await Workmanager().registerPeriodicTask(
    'deadline_reminders',
    BackgroundService.sendDeadlineRemindersTask,
    frequency: const Duration(hours: 24),
    initialDelay: const Duration(hours: 2),
  );
}
